/**
 * Database Migration: Add Enhanced Style Profile Fields
 * 
 * Adds new columns to support richer style profiling
 */

-- Add new columns to style_profiles table
ALTER TABLE style_profiles 
ADD COLUMN IF NOT EXISTS aesthetic_themes JSONB,
ADD COLUMN IF NOT EXISTS construction_patterns JSONB,
ADD COLUMN IF NOT EXISTS signature_pieces JSONB,
ADD COLUMN IF NOT EXISTS avg_confidence DECIMAL(3,3),
ADD COLUMN IF NOT EXISTS avg_completeness DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS style_tags TEXT[],
ADD COLUMN IF NOT EXISTS garment_types TEXT[],
ADD COLUMN IF NOT EXISTS style_description TEXT;

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_style_profiles_aesthetic_themes 
ON style_profiles USING GIN (aesthetic_themes);

CREATE INDEX IF NOT EXISTS idx_style_profiles_construction_patterns 
ON style_profiles USING GIN (construction_patterns);

-- Update existing rows with default values
UPDATE style_profiles 
SET 
  aesthetic_themes = '[]'::jsonb,
  construction_patterns = '[]'::jsonb,
  signature_pieces = '[]'::jsonb,
  avg_confidence = 0.5,
  avg_completeness = 0,
  style_tags = ARRAY[]::text[],
  garment_types = ARRAY[]::text[]
WHERE aesthetic_themes IS NULL;

-- Comments for documentation
COMMENT ON COLUMN style_profiles.aesthetic_themes IS 'Rich aesthetic descriptors (e.g., sporty-chic, equestrian, minimalist) with counts and examples';
COMMENT ON COLUMN style_profiles.construction_patterns IS 'Common construction details (e.g., quilting, pocket types, closures) across wardrobe';
COMMENT ON COLUMN style_profiles.signature_pieces IS 'High-confidence, distinctive items that define the users style';
COMMENT ON COLUMN style_profiles.avg_confidence IS 'Average confidence score across all analyzed images';
COMMENT ON COLUMN style_profiles.avg_completeness IS 'Average completeness percentage of image analysis';
COMMENT ON COLUMN style_profiles.style_tags IS 'Style tags generated by StyleTaggerAgent';
COMMENT ON COLUMN style_profiles.garment_types IS 'Normalized garment type list';
COMMENT ON COLUMN style_profiles.style_description IS 'Human-readable style description';
